// Project
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_LOGS = "UPDATE_PROJECT_LOGS";

// Project Commands
export const UPDATE_PROJECT_COMMAND_SERVICE = "UPDATE_PROJECT_COMMAND_SERVICE";
export const UPDATE_PROJECT_COMMAND_COMMAND = "UPDATE_PROJECT_COMMAND_COMMAND";
