// Project
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_LOGS = "UPDATE_PROJECT_LOGS";
export const TOGGLE_PROJECT_LOG_FILTER = "TOGGLE_PROJECT_LOG_FILTER";
export const CLEAR_PROJECT_LOG_FILTERS = "CLEAR_PROJECT_LOG_FILTERS";

// Project Commands
export const UPDATE_PROJECT_COMMAND_SERVICE = "UPDATE_PROJECT_COMMAND_SERVICE";
export const UPDATE_PROJECT_COMMAND_COMMAND = "UPDATE_PROJECT_COMMAND_COMMAND";
export const ADD_TO_PROJECT_COMMAND_HISTORY = "ADD_TO_PROJECT_COMMAND_HISTORY";
export const UPDATE_PROJECT_COMMAND_POINTER = "UPDATE_PROJECT_COMMAND_POINTER";
export const UPDATE_PROJECT_COMMAND_LOGS = "UPDATE_PROJECT_COMMAND_LOGS";
export const UPDATE_PROJECT_COMMAND_RUNNING = "UPDATE_PROJECT_COMMAND_RUNNING";
export const RESET_PROJECT_COMMAND_STATE = "RESET_PROJECT_COMMAND_STATE";
